services:
  core:
    build: ./docker-SquadJS
    restart: always
    container_name: squadjs-core-1
    volumes:
      - ./config.json:/home/app/SquadJS/config.json
      - ./docker-SquadJS/local-plugins:/home/app/local-plugins
      - ${SQUAD_DATA_PATH}/SquadGame/Saved/Logs:/home/app/logs
      - ${SQUAD_DATA_PATH}/SquadGame/ServerConfig/Admins.cfg:/home/app/admins/admins.cfg
    environment:
      - GIT_REPO=${GIT_REPO}
      - GIT_TAG=${GIT_TAG}
      - GIT_COMMIT=${GIT_COMMIT}
      - GIT_BRANCH=${GIT_BRANCH}
      - PLUGINS_LIST=${PLUGINS_LIST}